# -*- coding: utf-8 -*-
"""Multiple Chart in Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vTjHDCM_Ej9Qrr6v6WaRbW2cW07CHPtl
"""

import matplotlib.pyplot as plt
import numpy as np

def bar_chart():
    # Data
    categories = ['Apples', 'Bananas', 'Grapes', 'Oranges']
    values = [129, 135, 130, 225]

    # Plotting
    plt.bar(categories, values)
    plt.xlabel('Fruits')
    plt.ylabel('Quantity')
    plt.title('Bar Chart')
    plt.show()

def line_chart():
    # Data
    x = np.linspace(0, 10, 100)
    y = np.sin(x)

    # Plotting
    plt.plot(x, y)
    plt.xlabel('X')
    plt.ylabel('Y')
    plt.title('Line Chart')
    plt.show()

def scatter_plot():
    # Data
    x = np.random.rand(100)
    y = np.random.rand(100)

    # Plotting
    plt.scatter(x, y)
    plt.xlabel('X')
    plt.ylabel('Y')
    plt.title('Scatter Plot')
    plt.show()

def pie_chart():
    # Data
    labels = ['Apples', 'Bananas', 'Grapes', 'Oranges']
    sizes = [129, 135, 130, 225]

    # Plotting
    plt.pie(sizes, labels=labels, autopct='%1.1f%%')
    plt.title('Pie Chart')
    plt.show()

# Main function
def main():
    while True:
        print("Select a chart type to visualize:")
        print("1. Bar Chart")
        print("2. Line Chart")
        print("3. Scatter Plot")
        print("4. Pie Chart")
        print("0. Exit")
        choice = input("Enter your choice (0-4): ")

        if choice == '1':
            bar_chart()
        elif choice == '2':
            line_chart()
        elif choice == '3':
            scatter_plot()
        elif choice == '4':
            pie_chart()
        elif choice == '0':
            break
        else:
            print("Invalid choice. Please try again.")

if __name__ == '__main__':
    main()